title: Michele Orlandi
description: Developer and architect focused on distributed solutions for the next unprecedented, game-chaning, yet-to-be-announced, highly-anticipated hype
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker