apiVersion: v1
kind: Secret
metadata:
  name: cloudwatch-credentials
  namespace: openshift-logging
stringData:
  aws_access_key_id: {{ ENV.AWS_ID }}
  aws_secret_access_key: {{ ENV.AWS_KEY }}
---
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: logging
  namespace: openshift-logging
spec:
  managementState: Managed
  outputs:
    - cloudwatch:
        authentication:
          awsAccessKey:
            keyId:
              key: aws_access_key_id
              secretName: cloudwatch-credentials
            keySecret:
              secretName: cloudwatch-credentials
              key: aws_secret_access_key
          type: awsAccessKey
        groupName: two-preprod
        region: eu-central-1
        groupPrefix: rosa-{{ ENV.ROSA_CLUSTER_NAME }}
      type: cloudwatch
      name: output-two
    - cloudwatch:
        authentication:
          awsAccessKey:
            keyId:
              key: aws_access_key_id
              secretName: cloudwatch-credentials
            keySecret:
              secretName: cloudwatch-credentials
              key: aws_secret_access_key
          type: awsAccessKey
        groupName: one-preprod
        region: eu-central-1
        groupPrefix: rosa-{{ ENV.ROSA_CLUSTER_NAME }}
      type: cloudwatch
      name: output-one      
  pipelines:
  - name: integration-layer
    inputRefs:
    - application
    # - infrastructure
    outputRefs:
    - output-one
    filterRefs:
    - filter-one
  - name: mas
    inputRefs:
    - application
    # - infrastructure
    filterRefs:
    - filter-two
    outputRefs:
    - output-two
  serviceAccount:
    name: logging-collector
  filters:
    - name: filter-two
      type: drop
      drop:
        - test:
          - field: .kubernetes.namespace_name
            notMatches: "test1" 
          - field: .kubernetes.namespace_name
            notMatches: "test2"
          - field: .kubernetes.namespace_name
            notMatches: "test3"
          - field: .kubernetes.namespace_name
            notMatches: "test4"
    - name: filter-one
      type: drop
      drop:
        - test:
          - field: .kubernetes.namespace_name
            notMatches: "test5" 