apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: logging
spec:
  logging:
    lokiStack:
      name: logging-loki
  type: Logging
---      
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: forwarder
  namespace: openshift-logging
spec:
  serviceAccount:
    name: logging-collector
  filters:
    - name: test
      type: drop
      drop:
        - test:
          - field: .kubernetes.namespace_name
            notMatches: "test"         
  outputs:
  - name: default-lokistack
    type: lokiStack
    lokiStack:
      authentication:
        token:
          from: serviceAccount
      target:
        name: logging-loki
        namespace: openshift-logging
    tls:
      ca:
        key: service-ca.crt
        configMapName: openshift-service-ca.crt
  pipelines:
  - name: default-logstore
    inputRefs:
    - application
    # - infrastructure
    outputRefs:
    - default-lokistack
    filterRefs: 
    - test